### ISSUE TITLE
Change route params from type to function sig

### ISSUE THREAD

**Issue by agh4m** [Mycsina/DiSA-backend#21]

**Comment by Mycsina** [comment]
Já não me lembro sobre oq isto era, ainda te lembras? @agh4m

**Comment by agh4m** [comment]
> Já não me lembro sobre oq isto era, ainda te lembras? @agh4m 

Ya era para trocar alguns tipo que estao espalhados por argumentos nas funcoes dos pedidos pq havia algum mismatch

**Comment by Mycsina** [comment]
Há um no routes/collection que é +- propositado, mais algum?

**Comment by Mycsina** [comment]
@agh4m isto ainda é relevante?

**Comment by agh4m** [comment]
Provavelmente não, a menos que querias fazer um deep refactor dos enpoints quase todos (dos que vi)
